services:
  minio-api:
    image: minio/minio:RELEASE.2024-02-14T21-36-02Z
    container_name: minio-api
    env_file:
      - .env
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-api-data:/minio

volumes:
  minio-api-data:
